name: Web Automation Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # schedule:
  #   - cron: '20 05 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/dikako/pw-github-action:playwright-latest
            options: --workdir /app
        steps:
            - name: Run Tests
              run: |
                cd /app
                npx playwright test || true
                ls -l
                cd -r /app/playwright-report ./

            - name: Upload Test Artifacts
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: playwright-report

            - name: Deploy Test Report
              if: always()
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: /github/workspace/playwright-report
                publish_branch: gh-pages
